#!/usr/bin/env bash

set -eo pipefail

readonly GRAAL_VERSION="${GRAAL_VERSION:-22.3.1}"
readonly GRAAL_HOME="${GRAAL_HOME:-/opt/graalvm-ce-java17-${GRAAL_VERSION}}"

curl -sLO https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-$GRAAL_VERSION/graalvm-ce-java17-linux-amd64-$GRAAL_VERSION.tar.gz
tar -xzf graalvm-ce-java17-linux-amd64-$GRAAL_VERSION.tar.gz
${GRAAL_HOME}/bin/gu install native-image
